/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "REGION": "us-east-1",
    "USER_POOL_ID": "us-east-1_CX8YUvj2P",
    "USER_POOL_CLIENT_ID": "1hk52tg0mqsvvsjkoulfgasesk"
};


export default awsmobile;
