name: s3-deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      # Check if Amplify is configured
      - name: Check Amplify Configuration
        id: check-config
        run: |
          if [ -d "amplify" ]; then
            echo "::set-output name=isConfigured::true"
          else
            echo "::set-output name=isConfigured::false"
          fi
        working-directory: ./frontend

      # If Amplify is not configured, configure it
      - name: Configure Amplify
        if: steps.check-config.outputs.isConfigured == 'false'
        run: amplify configure --accessKeyId ${{ secrets.AWS_ACCESS_KEY_ID }} --secretAccessKey ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region ${{ secrets.AWS_REGION }} --yes

      # Initialize Amplify
      - name: Initialize Amplify
        run: cd frontend && amplify init --yes

      # Pull the latest backend changes
      - name: Pull Amplify Changes
        run: cd frontend && amplify pull --yes

      - name: Push Amplify Changes
        run: cd frontend && amplify push --yes

      - name: Build React App
        run: cd frontend && npm run build

      - name: Deploy build folder to S3 bucket
        run: aws s3 sync ./frontend/build s3://www.linktheweb.com --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
